### ISSUE TITLE
Is there an easy way to make a LATER entry to TODO?

### ISSUE THREAD

**Issue by liuxueyang** [omouse/org-doing#17]
Is there some command or I have to edit the `doing.org` file by myself?
Thanks for your plugin. ;-)

**Comment by omouse** [comment]
The eaiest way is to edit the file yourself, you could also create a new entry later that references the earlier one. I use org doing as a log, kind of like a stream of consciousness.

**Comment by glucas** [comment]
Like  @omouse I'm using org-doing for fast capture (usually from a shell) and just open the file in org-mode for other things like choosing what do to next, archiving done items, re-ordering tasks, etc. 

I could imagine augmenting `org-doing-done-most-recent-item` to look for the top LATER entry in the list and change it to TODO. That might be a handy thing for a shell-based workflow like this:

    doing task one             --> creates TODO task one
    doing later task two       --> creates LATER task two
    doing later task three     --> creates LATER task three
    doing done                 --> marks task one DONE, changes task two to TODO
    doing done                 --> marks task two DONE, changes task three to TODO
    doing done                 --> marks task three DONE

@liuxueyang Is that what you were thinking?

**Comment by glucas** [comment]
I took a first pass at this, to see if the idea might be useful. 

(Note the order of things in my example above is not exactly right. as Items 'task two' and 'task three' are added, 'task three' winds up higher in the list so it would get marked TODO before the other one.)

**Comment by glucas** [comment]
After trying this for a bit, I might prefer to have a separate action to promote the next LATER item, rather than doing it automatically. Something like:

    doing done   --> close the current TODO
    doing next   --> promote the first LATER item to TODO

**Comment by omouse** [comment]
closing this as we merged in the PR related to it 👍 

@liuxueyang I'll reopen if the the PR doesn't quite do what you wanted 😄

**Comment by liuxueyang** [comment]
Sorry for my ignore for Github notifications.
Great work. Thank you so much. @omouse @glucas
