### ISSUE TITLE
Is it possible to make "datetree" for entry as an option?

### ISSUE THREAD

**Issue by enzochiau** [omouse/org-doing#2]
Is it possible to make "datetree" for entry as an option?

**Comment by omouse** [comment]
@enzochiau could you give an example of what you mean? like expected output in the buffer?

**Comment by enzochiau** [comment]
Here is a simple example:

    * 2014
    ** 2014-12 December
    *** 2014-12-15 Monday
    **** item 1
    *** 2014-12-24 Wednesday
    **** item 4
    
    * 2015
    ** 2015-01 January
    *** 2015-01-01 Thursday
    **** item 3
    *** 2015-01-05 Monday
    **** item 2

**Comment by omouse** [comment]
Thanks for the example. The logic for this would require scanning for the
date and then inserting the heading. I'm not sure what the advantage of
this is since you can use org-agenda mode to filter out what's happening.

Rudolf
