### ISSUE TITLE
Close or hide the org-doing buffer after capturing a new entry

### ISSUE THREAD

**Issue by glucas** [omouse/org-doing#9]
This may be just a personal preference, but I'd like org-doing to behave more like org-capture and get out of the way after I add a new entry. Right now after you add an entry you are left looking at the org-doing file rather than whatever it was you were working on. 

I can do this locally with advice, but raising it here in case others would like that behavior -- either all the time or as a customization option.

**Comment by omouse** [comment]
so I attempted to write a unit test for this and use stub functions for save-buffer and bury-buffer and it didn't quite work. Right now I'm trying to get an ecukes set of tests working but it isn't quite working either, would be cool if @AdrieanKhisbe shed some light on how to define Then assertions.

@glucas your code looks good and I do prefer this behaviour. I think the default should be to bury the buffer and to have a custom variable to set this option.

**Comment by AdrieanKhisbe** [comment]
@omouse I'm just this notification. might be too late. :/ sorry
